Need to update
smirnovlad/MazeGeneration pull request #1
Opened 2022-04-07 19:21 UTC by smirnovlad

2022-04-08 16:42 UTC, salamantos requested changes
очень хорошо, буду рад поиграть в улучшенную версию)

2022-04-08 16:42 UTC, salamantos commented on main.py
> +    if mode == "1":
лучше не заставлять пользователя ждать генерации, а генерить после ввода всех команд или дать ему фидбек, что что-то генерится (без этого выглядит будто все зависло:) )

2022-04-08 16:42 UTC, salamantos commented on main.py
> +                        cell.walls['top'] = (matrix[i - 1][j] == 'w')
как-то супер запутанно получилось с такими символами) давай попробуем использовать какие-то другие, чтобы ВИЗУАЛЬНО легко было отличить стену от не-стены

2022-04-08 16:42 UTC, salamantos commented on README.md
> +Планирую всё структурировать: создавать для классов отдельные .py файлы и делать соответствующие импорты.
правки, с которыми просто огонь станет:

- [ ] сделать чтобы окно было видно при запуске
- [ ] сделать кнопки вместо консольных команд: неудобно и консоль и графику использовать, хочется все в одном окошке видеть
- [ ] как-то показать номера клеток, а еще лучше сделать их выбор по нажатию на клетку
- [ ] при решении сделать меньше интервал между появлением розовых квадратиков

2022-04-08 16:42 UTC, salamantos commented on main.py
> +import pygame
давай плз разобьем все на файлы и функции

2022-04-08 16:42 UTC, salamantos commented on main.py
> +                        cell.walls['top'] = (matrix[i - 1][j] == 'w')
если есть графика, может это вообще выпилить?)

2022-05-01 16:40 UTC, smirnovlad commented
Здравствуйте!
1. Добавил кнопки вместо консольный команд (необходимо установить дополнительный пакет tkinter: python-tkdnd в pycharm)
2. Добавил возможность выбора клетки при помощи клика мыши
3. Ну и уменьшил интервал между появлениями розовых квадратиков)
4. Все классы разбиты на отдельные файлы. Как смог..)

2023-03-20 06:48 UTC, merged